#ifndef AUTOGENERATED_H
#define AUTOGENERATED_H

#include <algorithm>
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include "User.h"
#include "backend.h"

void import_data(std::ifstream &, std::unordered_map<unsigned, User> &, std::unordered_map<unsigned, Group> &);
void auto_run(std::unordered_map<unsigned, User> &user_list, std::unordered_map<unsigned, Group> &group_list);

#endif