import csv
import random
import string
import os

users_number  = 2
groups_number = 15

transactions_number = 50 # Total amount of transactions in all groups

min_group_members_count = 2
max_group_members_count = 2 #must <= users_number

# Expense amount in Euro
min_expense_amount = 2
max_expense_amount = 100

min_char_in_name_count = 5
max_char_in_name_count = 10

file_name = 'autogenerated_file.csv' # File name to save generated data

def generate_random_username():
    return ''.join(random.choices(string.ascii_letters, k=random.randint(min_char_in_name_count, max_char_in_name_count)))

def generate_auto_file(users_count=users_number, groups_count=groups_number, transactions_count=transactions_number ):
    # Generate random user data
    users = [ f'User_{i}' for i in range(users_count)]

    # Generate random group data
    groups = [{'GroupName': f'Group_{i}', 'Members': random.sample(users, random.randint(min_group_members_count, max_group_members_count))} for i in range(groups_count)]

    # Generate random expenses with multiple receivers
    expenses = []
    for i in range(transactions_count):
        group = random.choice(groups)
        expense =  {'Group': group['GroupName'],
                    'Sender': random.choice(group['Members']),
                    'Receivers': random.sample([user for user in group['Members']], random.randint(1, min(30,len(group['Members'])))),
                    'Amount': random.randint(min_expense_amount, max_expense_amount)}
        expenses.append(expense)

    # Find current path
    current_directory = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(current_directory, file_name)
    # Write data to CSV file
    with open(path, mode='w', newline='') as file:
        writer = csv.writer(file)

        # Write user data
        writer.writerow(['Users'])
        for user in users:
            writer.writerow([user])

        # Write group data
        writer.writerow(['Groups'])
        for group in groups:
            members = ','.join(member for member in group['Members'])
            writer.writerow([group['GroupName'], members])

        # Write expenses
        writer.writerow(['Expenses'])
        for expense in expenses:
            receivers = ','.join(expense['Receivers'])
            writer.writerow([expense['Group'], expense['Sender'], receivers, expense['Amount']])

if __name__ == "__main__":
    generate_auto_file()
