#include <string>
#include "../inc/frontend.h"
#include "../inc/auto_generate.h"

int main()
{

    auto data = "../autogenerated_data/autogenerated_file.csv";

    // Define frontend variables
    unsigned screen_id{0};
    unsigned user_id{};
    unsigned group_id{};

    // Define input Variables
    unsigned input_int{};
    float input_float{};
    std::string input_str{};

    // Define backend variables
    std::unordered_map<unsigned, User> user_umap{};
    std::unordered_map<unsigned, Group> group_umap{};

    // Init screen
    screen_id = 1;

    std::cout << "Choose mode:" << std::endl;
    std::cout << "(1): User mode" << std::endl;
    std::cout << "(2): Auto generated mode (for performance test)" << std::endl;
    std::cin >> screen_id;
    if (screen_id == 1)
    {
        // Start Terminal Loop
        while (true)
        {
            update_terminal(screen_id, user_id, group_id,
                            user_umap, group_umap);

            get_and_compute_input(input_int, input_float, input_str,
                                  screen_id, user_id, group_id,
                                  user_umap, group_umap);

            if ((screen_id == 0) && (input_int == 0))
            {
                break;
            }
        }
    }
    else
    {
        // autogenerated file
        std::ifstream file(data);

        import_data(file, user_umap, group_umap);
        auto_run(user_umap, group_umap);
    }
    return 0;
}
