#include <string>
#include "frontend.h"
#include "auto_generate.h"

int main()
{

    auto data = "../autogenerated_data/autogenerated_file.csv";

    // Define frontend variables
    int screen_id{0};
    int user_id{};
    int group_id{};

    // Define input Variables
    int input_int{};
    float input_float{};
    std::string input_str{};

    // Define backend variables
    std::vector<User> user_list{};
    std::vector<Group> group_list{};

    // Init screen
    screen_id = 1;

    std::cout << "Choose mode:" << std::endl;
    std::cout << "(1): User mode" << std::endl;
    std::cout << "(2): Auto generated mode (for performance test)" << std::endl;
    std::cin >> screen_id;
    if (screen_id == 1)
    {
        // Start Terminal Loop
        while (true)
        {
            update_terminal(screen_id, user_id, group_id,
                            user_list, group_list);

            get_and_compute_input(input_int, input_float, input_str,
                                  screen_id, user_id, group_id,
                                  user_list, group_list);

            if ((screen_id == 0) && (input_int == 0))
            {
                break;
            }
        }
    }
    else
    {
        // autogenerated file
        std::ifstream file(data);

        import_data(file, user_list, group_list);
        auto_run(user_list, group_list);
    }
    return 0;
}
